"""Loads a CSV file into a nominated SQLite3 database.

The csv file is generated by Google Play Developer Console and
downloaded to the local machine prior to loading the file. The 
database is expected to already have the reviews table.

Limitations: no known deduping or data validation.
"""
import argparse

"""
>>> with open(mycsv, 'r', encoding='utf16') as csvf:
...     has_header = csv.Sniffer().has_header(csvf.read(1024))
...     csvf.seek(0)
...     incsv = csv.reader(csvf)
...     if has_header:
...         next(incsv)
...     with sqlite3.connect('reviews.db') as conn:
...         cursor = conn.cursor()
...         cursor.executemany('insert into reviews values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', incsv)
...     conn.close()
... 
"""

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("csvfilewithreviews", help="File with reviews downloaded from Google Play Developer Console in CSV format.")
    parser.add_argument("db", help="Existing SQLite3 database to add reviews to.")
    args = parser.parse_args()
    print(args.csvfilewithreviews)
    print(args.db)
