# automatically generated by the FlatBuffers compiler, do not modify

# namespace: review

import flatbuffers

class Review(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReview(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Review()
        x.Init(buf, n + offset)
        return x

    # Review
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Review
    def PackageName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def AppVersionCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Review
    def AppVersionName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def ReviewerLanguage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def Device(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def ReviewSubmitDateAndTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def ReviewSubmitMillisSinceEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Review
    def ReviewLastUpdateDateAndTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def ReviewLastUpdateMillisSinceEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Review
    def ReviewStarRating(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Review
    def ReviewTitle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def ReviewText(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def DeveloperReplyDataAndTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def DeveloperReplyMillisSinceEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Review
    def DeveloperReplyText(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Review
    def ReviewLink(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def ReviewStart(builder): builder.StartObject(16)
def ReviewAddPackageName(builder, packageName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(packageName), 0)
def ReviewAddAppVersionCode(builder, appVersionCode): builder.PrependInt32Slot(1, appVersionCode, 0)
def ReviewAddAppVersionName(builder, appVersionName): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(appVersionName), 0)
def ReviewAddReviewerLanguage(builder, reviewerLanguage): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(reviewerLanguage), 0)
def ReviewAddDevice(builder, device): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(device), 0)
def ReviewAddReviewSubmitDateAndTime(builder, reviewSubmitDateAndTime): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(reviewSubmitDateAndTime), 0)
def ReviewAddReviewSubmitMillisSinceEpoch(builder, reviewSubmitMillisSinceEpoch): builder.PrependInt64Slot(6, reviewSubmitMillisSinceEpoch, 0)
def ReviewAddReviewLastUpdateDateAndTime(builder, reviewLastUpdateDateAndTime): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(reviewLastUpdateDateAndTime), 0)
def ReviewAddReviewLastUpdateMillisSinceEpoch(builder, reviewLastUpdateMillisSinceEpoch): builder.PrependInt64Slot(8, reviewLastUpdateMillisSinceEpoch, 0)
def ReviewAddReviewStarRating(builder, reviewStarRating): builder.PrependInt32Slot(9, reviewStarRating, 0)
def ReviewAddReviewTitle(builder, reviewTitle): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(reviewTitle), 0)
def ReviewAddReviewText(builder, reviewText): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(reviewText), 0)
def ReviewAddDeveloperReplyDataAndTime(builder, developerReplyDataAndTime): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(developerReplyDataAndTime), 0)
def ReviewAddDeveloperReplyMillisSinceEpoch(builder, developerReplyMillisSinceEpoch): builder.PrependInt64Slot(13, developerReplyMillisSinceEpoch, 0)
def ReviewAddDeveloperReplyText(builder, developerReplyText): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(developerReplyText), 0)
def ReviewAddReviewLink(builder, reviewLink): builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(reviewLink), 0)
def ReviewEnd(builder): return builder.EndObject()
